name: cc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - bowtie2>=2.4.4
  - click<=8.1.0
  - cooler
  - cookiecutter
  - fastqc
  - flash
  - ibis-framework>=6.0.0
  - iced
  - joblib
  - loguru
  - multiqc
  - numpy<=1.23
  - pandas<=2.0.1
  - papermill
  - pip<=22.2.2
  - plotly>5.0.0,<=5.15.0
  - pyarrow>8.0.0,<=9.0.0
  - pybedtools
  - pyranges
  - pysam>0.15.0,<=0.19.1
  - python-duckdb
  - python-xxhash
  - python>=3.10,<3.11
  - quarto
  - ray-core>=2.6.0
  - samtools
  - seaborn
  - setuptools>50.1.0,<=65.0.1
  - snakemake<=7.30.2
  - tqdm
  - trackhub
  - trim-galore
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
  - ucsc-fetchchromsizes
  - ujson
