name: cc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools<=2.31.0
  - bowtie2>=2.4.4
  - click<=8.1.0
  - cooler<=0.9.2
  - cookiecutter<=2.1.1
  - fastqc<=0.12.1
  - flash<=1.2.11
  - ibis-framework>=6.0.0,<=7.0.0
  - iced<=0.5.10
  - joblib<=1.2.0
  - loguru
  - multiqc
  - numpy<=1.23
  - pandas<=2.0.1
  - papermill
  - pip<=22.2.2
  - panel<=1.3.0
  - pandera<=0.17.1
  - pydantic<=2.4.2
  - plotly>5.0.0,<=5.15.0
  - pyarrow>8.0.0,<12.0.0
  - pybedtools<=0.9.0
  - pyranges<=0.0.127
  - pysam>0.19.1,<=0.22.0
  - python-duckdb>0.9.0,<=0.9.1
  - python-xxhash>=3.4.1
  - python>=3.10,<=3.11
  - quarto
  - samtools<=1.15.1
  - seaborn<=0.12.2
  - setuptools>50.1.0,<=65.0.1
  - snakemake<=7.30.2
  - tqdm<=4.65.0
  - trackhub<=0.2.4
  - trim-galore<=0.6.10
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
  - ucsc-fetchchromsizes
  - ujson<=5.7.0
