name: cc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools<=2.31.0
  - bowtie2>=2.4.4
  - cxx-compiler
  - fastqc<=0.12.1
  - flash<=1.2.11
  - git
  - iced<=0.5.10
  - jupyterlab
  - pairix
  - pip
  - quarto
  - samtools<=1.15.1
  - trim-galore<=0.6.10
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
  - pip:
    - "pydantic>2.5"
    - "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl"
    - capcruncher-tools>=0.1.16
    - capcruncher[full]>=0.3.10
    - click<=8.2.0
    - cookiecutter<=2.1.1
    - cooler<=0.9.2
    - exceptiongroup
    - grpcio
    - h5py
    - ibis-framework[duckdb]>7.1.0,<=8.0.0
    - iced
    - joblib
    - loguru<=0.7.2
    - more-itertools
    - multiqc
    - pandas<=2.1.2
    - pandera
    - panel<=1.3.0
    - papermill
    - plotly>5.0.0,<=5.18.0
    - polars<=0.19.15
    - pyarrow>=14.0.1,<15.0.0
    - pybedtools<=0.9.0
    - pydantic>=2.5.0,<2.6
    - pypairix
    - pyranges<=0.0.127
    - pysam>0.15.0,<=0.21.0
    - pytest
    - pytest-cov
    - pytest-order
    - pytest-xdist
    - seaborn<=0.12.2
    - snakemake_wrapper_utils
    - snakemake<=7.32.4
    - tqdm<=4.65.0
    - trackhub<=0.2.4
    - tracknado
    - ujson<=5.7.0
    - xopen
    - xxhash<=3.4.1
