name: cc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - bowtie2>=2.4.4
  - click<=8.1.0
  - cooler
  - dask>2020.12.0,<=2022.8.0
  - fastqc
  - flash
  - ibis-framework>=6.0.0
  - iced
  - joblib
  - more-itertools
  - multiqc
  - natsort
  - numpy<=1.23
  - papermill
  - pandas<=1.5.2
  - pip<=22.2.2
  - plotly>5.0.0,<=5.10.0
  - pyarrow>8.0.0,<=9.0.0
  - pybedtools
  - pyranges
  - pysam>0.15.0,<=0.19.1
  - python-duckdb
  - python-xxhash
  - python>=3.10,<3.11
  - ray-core
  - samtools
  - seaborn
  - setuptools>50.1.0,<=65.0.1
  - snakemake>=7.30.1
  - tqdm
  - trackhub
  - trim-galore
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
  - ucsc-fetchchromsizes
  - ujson
  - quarto
